# Generated by Django 3.0.4 on 2020-03-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0002_delete_newsletter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zoouser',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='zoouser',
            name='last_name',
            field=models.CharField(default='lastname', max_length=100),
            preserve_default=False,
        ),
    ]
