# Generated by Django 3.0.4 on 2020-03-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0003_auto_20200327_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoouser',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
