# Generated by Django 3.0.4 on 2020-03-27 18:53

from django.db import migrations, models
import zoo.models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0004_auto_20200327_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoouser',
            name='first_name',
            field=models.CharField(max_length=100, validators=[zoo.models.validate_name, zoo.models.validate_name_length]),
        ),
        migrations.AlterField(
            model_name='zoouser',
            name='last_name',
            field=models.CharField(max_length=100, validators=[zoo.models.validate_name, zoo.models.validate_name_length]),
        ),
    ]
